
service: faaskeeper

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

package:
  include:
    - faaskeeper/aws/**
    - faaskeeper/core/**
  exclude:
    - faaskeeper/**
    - config/**
    - python-venv/**

functions:
  writer:
    handler: faaskeeper/aws/writer.handler
    events:
      - http:
          path: fk
          method: POST

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-write-queue
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE

