service: faaskeeper

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: faaskeeper
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/faaskeeper.json

frameworkVersion: '2'
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - faaskeeper/**
    - config/**
    - node_modules/**
    - node-venv/**
    - python-venv/**
  include:
    - server/faaskeeper/gcp/**
    - server/faaskeeper/core/**
    - server/faaskeeper/__init__.py
    - main.py

functions:
  server:
    handler: http
    events:
      - http: path
        authLevel: anonymous

