name: faaskeeper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: [3.7]
         #python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          tools/linting.py functions
          tools/linting.py tests
      - name: Test with pytest
        run: |
          FK_TEST_SERVICE_PORT=5000 FK_TEST_SERVICE_REGION="us-east-1" FK_TEST_SERVICE_NAME="faaskeeper-dev-marcin" pytest tests

